# Generated by Django 4.1.1 on 2022-09-10 19:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='작가 이름')),
                ('gender', models.CharField(choices=[(0, '여성'), (1, '남성')], max_length=4, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생일')),
                ('email', models.EmailField(max_length=80, verbose_name='이메일')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='연락처')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userinfos',
            },
        ),
        migrations.CreateModel(
            name='ApplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('examine_date', models.DateField(default=None, null=True)),
                ('is_approval', models.BooleanField(default=None, null=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            options={
                'db_table': 'approval_log',
            },
        ),
    ]
