# Generated by Django 4.1.1 on 2022-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_applylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=80, unique=True, verbose_name='이메일'),
        ),
    ]
